version: "2"
services:
  krameriusinit:
    build: krameriusinit
    environment:
      - krameriusHost=http://kramerius:8080/search
    volumes:
      - /tmp/k5init:/opt/app-root/src/.kramerius4/import
    networks:
      - kramerius
  kramerius:
    image: kramerius
    ports:
      - "8080:8080"
    volumes:
      - /tmp/k5init:/opt/app-root/src/.kramerius4/import
    networks:
      - kramerius
    environment:
      - fedoraHost=http://fcrepo:8080/fedora
      - fedoraUser=fedoraAdmin
      - fedoraPass=fedoraAdmin
      - fedora3_connectionURL=jdbc:postgresql://fedoraPostgres:5432/fedora3
      - fedora3_connectionUser=fedoraAdmin
      - fedora3_connectionPass=fedoraAdmin
      - kramerius_connectionURL=jdbc:postgresql://krameriusPostgres:5432/kramerius
      - kramerius_connectionUser=fedoraAdmin
      - kramerius_connectionPass=fedoraAdmin
      - driver_fedora_mpt_jdbc_url=jdbc:postgresql://riTriplesPostgres:5432/riTriples
      - driver_fedora_mpt_jdbc_user=fedoraAdmin
      - driver_fedora_mpt_jdbc_password=fedoraAdmin
      - solrHost=http://solr:8080/solr
      - applicationUrl=http://kramerius:8080/search
  krameriusPostgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=fedoraAdmin
      - POSTGRES_PASSWORD=fedoraAdmin
      - POSTGRES_DB=kramerius
    networks:
      - kramerius
  fcrepo:
    image: moravianlibrary/fcrepo:3.8.1
    networks:
      - kramerius
  fedoraPostgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=fedoraAdmin
      - POSTGRES_PASSWORD=fedoraAdmin
      - POSTGRES_DB=fedora3
    networks:
      - kramerius
  riTriplesPostgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=fedoraAdmin
      - POSTGRES_PASSWORD=fedoraAdmin
      - POSTGRES_DB=riTriples
    networks:
      - kramerius
  solr:
    image: moravianlibrary/solr
    networks:
      - kramerius
networks:
  kramerius:
    driver: bridge
