kramerius:
  image: kramerius
  ports:
    - "8080:8080"
  links:
    - krameriusPostgres:krameriusPostgres
    - solr:solr
  environment:
    - fedoraHost=http://fcrepo:8080/fedora
    - fedoraUser=fedoraAdmin
    - fedoraPass=fedoraAdmin
    - fedora3.connectionURL=jdbc:postgresql://fedoraPostgres:5432/fedora3
    - fedora3.connectionUser=fedoraAdmin
    - fedora3.connectionPass=fedoraAdmin
    - driver.fedora.mpt.jdbc.url=jdbc:postgresql://riTriplesPostgres:5432/riTriples
    - driver.fedora.mpt.jdbc.user=fedoraAdmin
    - driver.fedora.mpt.jdbc.password=fedoraAdmin
    - solrHost=http://solr:8080/solr
krameriusPostgres:
  image: "postgres:9.3"
  environment:
    - POSTGRES_USER=fedoraAdmin
    - POSTGRES_PASSWORD=fedoraAdmin
    - POSTGRES_DB=kramerius4
fcrepo:
  image: moravianlibrary/fcrepo:3.6.2
  links:
    - fedoraPostgres:fedoraPostgres
    - riTriplesPostgres:riTriplesPostgres
fedoraPostgres:
  image: "postgres:9.3"
  environment:
    - POSTGRES_USER=fedoraAdmin
    - POSTGRES_PASSWORD=fedoraAdmin
    - POSTGRES_DB=fedora3
riTriplesPostgres:
  image: "postgres:9.3"
  environment:
    - POSTGRES_USER=fedoraAdmin
    - POSTGRES_PASSWORD=fedoraAdmin
    - POSTGRES_DB=riTriples
solr:
  image: moravianlibrary/solr
